local_planner:
  ros__parameters:

    # STRATEGY: MOVING STRAIGHT
    moving_straight_kp: 2.0
    moving_straight_kd: 0.0
    moving_straight_ki: 0.0
    moving_straight_initial_pwm: 1500 # initial speed
    moving_straight_angle_tolerance: 15.0 # will only correct angle while moving straight if greater than this angle
    moving_straight_forward_prediction_step: 1 

    # STRATEGY: TURNING
    turning_kp: 3.0
    turning_kd: 0.7
    turning_ki: 0.5
    turning_prediction_step: 1

    # PWM
    max_pwm: 1765
    min_pwm: 992
    neutral_pwm: 1376

    # OTHER
    autonomous_controller_frequency: 10
    distance_error_tolerance: 0.5
    local_plan_step_size: 1