local_planner:
  ros__parameters:

    # PWM
    min_pwm: 992
    neutral_pwm: 1376
    max_pwm: 1765

    # STATE: STRAIGHT
    straight_initial_pwm: 30.0 # percent
    straight_adjustment_pwm: 2.0 # percent
    straight_angle_tolerance: 5.0 # degrees - will only correct angle difference if outside this tolerance
    straight_distance_tolerance: 1.0 # meters - will stop once within this distance of the waypoint

    # STATE: TURN
    turn_initial_pwm: 10.0 # percent
    turn_angle_tolerance: 5.0 # will begin straight state once angle difference is within this tolerance

    # OTHER
    process_frequency: 10 # Hz (times / second)