local_planner:
  ros__parameters:

    # PWM
    min_pwm: 992
    neutral_pwm: 1376
    max_pwm: 1765

    # STATE: STRAIGHT
    straight_initial_pwm: 30.0 # percent - forward speed of mower
    straight_distance_tolerance: 1.0 # meters - will stop once within this distance of the waypoint
    straight_kp: 0.517  # Proportional coefficient of PID equation
    straight_ki: 0.0  # Integral coefficient of PID equation
    straight_kd: 0.0  # Derivitive coefficient of PID equation

    # STATE: TURN
    turn_max_pwm: 30.0 # percent
    turn_angle_tolerance: 5.0 # will begin straight state once angle difference is within this tolerance
    turn_kp: 0.776  # Proportional coefficient of PID equation
    turn_ki: 0.129  # Integral coefficient of PID equation
    turn_kd: 0.181  # Derivitive coefficient of PID equation

    # OTHER
    process_frequency: 10 # Hz (times / second)