/**:
    ros__parameters:
        PUBLISH_RATE: 200 # in HZ
        X_ACCURACY: 0.3
        Y_ACCURACY: 0.3
        Z_ACCURACY: 0.0001
        ROLL_ACCURACY: 0.0001
        PITCH_ACCURACY: 0.0001
        YAW_ACCURACY: 0.1
        VELOCITY_X_ACCURACY: 0.3
        VELOCITY_Y_ACCURACY: 0.3
        VELOCITY_Z_ACCURACY: 0.0001
        VELOCITY_ROLL_ACCURACY: 0.00001
        VELOCITY_PITCH_ACCURACY: 0.00001
        VELOCITY_YAW_ACCURACY: 0.1