/**: 
  ros__parameters:
    LEFT_NEUTRAL: 1376 # Left neutral pwm
    RIGHT_NEUTRAL: 1376
    RIGHT_MAX: 1765 # RIGHT_NEUTRAL+ Increase in right servo's pwm
    LEFT_MAX: 1765 # LEFT_NEUTRAL+ Increase in left servo's pwm
    RIGHT_MIN: 992 # LEFT_NEUTRAL+ Decrease in left servo's pwm
    LEFT_MIN: 992  # RIGHT_NEUTRAL+ Decrease in right servo's pwm
    WHEEL_RADIUS: 0.2159
    WHEEL_SEPARATION: 0.889
    KNOW_LEFT_FULL_BACKWARD_SPEED: -1.0 # in meter/second
    KNOW_RIGHT_FULL_BACKWARD_SPEED: -1.0
    KNOW_LEFT_FULL_FORWARD_SPEED: 1.0
    KNOW_RIGHT_FULL_FORWARD_SPEED: 1.0     # (68 *pi*0.4318)/60
    PUBLISH_RATE: 200 # in HZ
