
teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 2.0  # max speed is 2 m/s
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 2.2 # max speed is 2.2 rad/s

    enable_button: 2  # Left trigger button
    enable_turbo_button: -1   # Right trigger button
    